In [44]:
import numpy as np


In [45]:
a=np.array([[1,2],[6,7]])  #2x2 Array
b=np.array([[11,12],[16,17]]) #2x2 array

In [46]:
print(a[0:2,1:2]) # Print a slice of array

[[2]
 [7]]


In [47]:
print(a)  # Print the entire array 'a'
print(b)  # Print the entire array 'b'

mul=np.dot(a,b) # Calculate the dot element of 'a' and 'b'
print(mul) # Print the result of the dot element


[[1 2]
 [6 7]]
[[11 12]
 [16 17]]
[[ 43  46]
 [178 191]]


In [48]:
mul1=np.multiply(a,b) # multiplication of a and b
print(mul1) # Print the result of multiplication

[[ 11  24]
 [ 96 119]]


In [49]:
add1=np.add(a,b) # Calculate addition of a and b
print(add1) # Print the result of addition

[[12 14]
 [22 24]]


In [51]:
sub=np.subtract(a,b)  # Calculate subtraction of 'b' from 'a'
print(sub) # Print the result of subtraction

[[-10 -10]
 [-10 -10]]


In [52]:
dev=np.divide(a,b) # Calculate element-wise division of 'a' by 'b'
print(dev) # Print the result of element-wise division

[[0.09090909 0.16666667]
 [0.375      0.41176471]]


In [53]:
n1=np.array([[10,20,30],[40,50,60]]) # Create a 2x3 NumPy array named 'n1'
n2=np.array([[15,25,35],[45,55,65]]) # Create a 2x3 NumPy array named 'n2'
div1=np.divide(n1,n2) # Calculate element-wise division of 'n1' by 'n2'
print(div1) # Print the result of element-wise division

[[0.66666667 0.8        0.85714286]
 [0.88888889 0.90909091 0.92307692]]


In [54]:
n3=np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])  # Create a 1D NumPy array named 'n3'
re=n3.reshape(4,4) # Reshape 'n3' into a 4x4 array
print(re) # Print the reshaped array

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [55]:
print(n3.min()) # Print the minimum value in 'n3'
print(n3.max())  # Print the maximum value in 'n3'
print(re.max(axis=1)) # Print max along each row
print(re.min(axis=0)) # Print min along each column

10
160
[ 40  80 120 160]
[10 20 30 40]


In [56]:
print(n1)  # Print array 'n1'
print(np.sqrt(n1)) # Print the square root of each element in 'n1'
print(np.std(n1)) # Print the standard deviation of 'n1'

[[10 20 30]
 [40 50 60]]
[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]
17.07825127659933


In [57]:
v=np.vstack((n1,n2))  # Vertically stack 'n1' and 'n2'
print(v)  # Print the vertically stacked array
h=np.hstack((n1,n2)) # Horizontally stack 'n1' and 'n2'
print(h) # Print the horizontally stacked array

[[10 20 30]
 [40 50 60]
 [15 25 35]
 [45 55 65]]
[[10 20 30 15 25 35]
 [40 50 60 45 55 65]]


In [58]:
arr=np.arange(0,20,3) # Create an array from 0 to 20 with a step of 3
print(arr) # Print the array

[ 0  3  6  9 12 15 18]


In [59]:
arr=np.arange(0,50,3,float) # Create an array from 0 to 50 with a step of 3, as float
print(arr) # Print the float array
print(arr.dtype) # Print the data type of the array

[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36. 39. 42. 45. 48.]
float64


In [60]:
arr=np.linspace(0,50,3) # Create 3 evenly spaced numbers from 0 to 50
print(arr) # Print the linearly spaced array
print(arr.dtype) # Print the data type of array

[ 0. 25. 50.]
float64


In [61]:
hr=h.T # Transpose array 'h'
print(hr) # Print the transposed array


[[10 40]
 [20 50]
 [30 60]
 [15 45]
 [25 55]
 [35 65]]


In [62]:
for i in np.nditer(hr): # Iterate through each element of transposed array
    print("AK",i) # Print each element

AK 10
AK 20
AK 30
AK 15
AK 25
AK 35
AK 40
AK 50
AK 60
AK 45
AK 55
AK 65


In [63]:
print(np.exp(n1)) # Calculate and print element-wise exponential of n1

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [64]:
print(np.sin(n1)) # Calculate and print element-wise sine of n1

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [65]:
print(np.cos(n1)) # Calculate and print element-wise cosine of n1

[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [66]:
print(np.log(n1)) # Calculate and print element-wise natural log of n1

[[2.30258509 2.99573227 3.40119738]
 [3.68887945 3.91202301 4.09434456]]


In [67]:
print(np.sum(n1))  # Print sum of all elements in n1

210


In [68]:
print(np.std(n1)) # Print standard deviation of n1

17.07825127659933


In [69]:
from scipy import stats as st # Import stats module from scipy library
print('mean',np.mean(n1)) # Print the mean of n1

mean 35.0


In [70]:
print('Median',np.median(n1)) # Print the median of n1

Median 35.0


In [71]:
print('Mode',st.mode(n1)) # Print the mode of n1 using scipy.stats

Mode ModeResult(mode=array([[10, 20, 30]]), count=array([[1, 1, 1]]))


In [75]:
n3=np.array([[1,2,3],[4,5,6]])
print(format(n3.shape))

(2, 3)
